### ISSUE TITLE
Calibration for knightsbridge-cu9kw

### ISSUE THREAD

**Issue by Cenedd** [DJBenson/ha-stuff#1]
I've used your code as a base for these sockets - thanks for that.  I've added in calibration for the voltage, power and current.
The code for that is borrowed (shamelessly) from here:  https://github.com/LocalBytes/esphome-localbytes-plug/blob/main/localbytes-plug-pm.yaml
I'm not sure of the mass deployment parts of the config so this is a one-off config with some passwords cut.  Just in case it's of use to you or anyone else.

```
substitutions:
  devicename: "esp-sockets"
  devicename_upper: ESP-Sockets

esphome:
  name: $devicename
  friendly_name: $devicename_upper

esp8266:
  # No idea what kind of board is it so using a generic one
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<snip>"
  services:
    - service: calibrate_voltage
      variables:
        actual_value: float
      then:
        - lambda: |-
            id(voltage_multiply) = actual_value / id(voltage).raw_state;
        - number.set:
            id: voltage_factor
            value: !lambda "return id(voltage_multiply);"

    - service: calibrate_power
      variables:
        actual_value: float
      then:
        - lambda: |-
            id(power_multiply) = actual_value / id(power).raw_state;
        - number.set:
            id: power_factor
            value: !lambda "return id(power_multiply);"

    - service: calibrate_current
      variables:
        actual_value: float
      then:
        - lambda: |-
            id(current_multiply) = actual_value / id(current).raw_state;
        - number.set:
            id: current_factor
            value: !lambda "return id(current_multiply);"
ota:
  - platform: esphome
    password: "<snip>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename Hotspot"
    password: "<snip>"

time:
  - platform: homeassistant
    timezone: Europe/London

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

globals:
  - id: voltage_multiply
    type: float
    restore_value: true
    initial_value: "0.859"  #This is about right - at least for my sockets

  - id: power_multiply
    type: float
    restore_value: true
    initial_value: "0.835" #This is about right - at least for my sockets

  - id: current_multiply
    type: float
    restore_value: true
    initial_value: "0.898" #This is about right - at least for my sockets


captive_portal:

output:
  - platform: gpio
    id: relay_1
    pin: GPIO15 # relay 1
  - platform: gpio
    id: relay_2
    pin: GPIO4 # relay 2
  - platform: gpio
    id: led_1
    pin: 
      number: GPIO2 # led 1
      inverted: true
  - platform: gpio
    id: led_2
    pin: 
      number: GPIO0 # led 2
      inverted: true

switch:
  - platform: output
    output: relay_1
    name: "$devicename Outlet 1"
    id: cu9kw_socket_1
    icon: mdi:power-socket-uk
    on_turn_on:
      - output.turn_on: led_1
    on_turn_off:
      - output.turn_off: led_1
  - platform: output
    name: "$devicename Outlet 2"
    id: cu9kw_socket_2
    output: relay_2
    icon: mdi:power-socket-uk
    on_turn_on:
      - output.turn_on: led_2
    on_turn_off:
      - output.turn_off: led_2

binary_sensor:

  - platform: gpio
    id: button_1
    pin:
      number: GPIO16 # button 1
      mode:
        input: true
        pullup: false # GPIO16 doesn't have a pullup resistor
      inverted: false
    on_press:
      - switch.toggle: cu9kw_socket_1

  - platform: gpio
    id: button_2
    pin:
      number: GPIO13 # button 2
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      - switch.toggle: cu9kw_socket_2

sensor:
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  - platform: wifi_signal
    name: "$devicename_upper WiFi Signal Sensor"
    update_interval: 60s

  - platform: uptime
    name: "$devicename_upper Uptime Sensor"

  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO5
    cf1_pin: GPIO14
    update_interval: 10s
    voltage:
      name: "Voltage"
      id: voltage
      unit_of_measurement: V
      accuracy_decimals: 1
      filters:
        - lambda: return x * id(voltage_multiply);
        
    power:
      name: "Power"
      id: power
      unit_of_measurement: W
      accuracy_decimals: 0
      filters:
        - lambda: return x * id(power_multiply);
        
    current:
      name: "Current"
      id: current
      unit_of_measurement: A
      accuracy_decimals: 3
      filters:
        - lambda: return x * id(current_multiply);
          
  # Total daily energy sensor
  - platform: total_daily_energy
    name: "Daily Energy"
    device_class: energy
    power_id: power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

# Make calibration factor data readable/setable from home assistant
number:
  - platform: template
    name: "Voltage Calibration Factor"
    id: voltage_factor
    icon: "mdi:sine-wave"
    min_value: 0
    max_value: 10
    step: 0.001
    entity_category: diagnostic
    mode: box
    lambda: |-
      return id(voltage_multiply);
    set_action:
      lambda: |-
        id(voltage_multiply) = x;

  - platform: template
    name: "Power Calibration Factor"
    id: power_factor
    icon: "mdi:flash"
    min_value: 0
    max_value: 10
    step: 0.001
    entity_category: diagnostic
    mode: box
    lambda: |-
      return id(power_multiply);
    set_action:
      lambda: |-
        id(power_multiply) = x;

  - platform: template
    name: "Current Calibration Factor"
    id: current_factor
    icon: "mdi:current-ac"
    min_value: 0
    max_value: 10
    step: 0.001
    entity_category: diagnostic
    mode: box
    lambda: |-
      return id(current_multiply);
    set_action:
      lambda: |-
        id(current_multiply) = x;

button:
  - platform: restart
    name: "$devicename Restart"
#  - platform: safe_mode
#    name: "$devicename Restart (Safe Mode)"
#  - platform: factory_reset
#    name: "$devicename Factory Reset"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "SSID"
    bssid:
      name: "BSSID"
    mac_address:
      name: "Mac Address"
  - platform: template
    name: Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start
```
